# Generated by Django 3.1.5 on 2021-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0018_theme_list_filter_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='action_buttons_sticky',
            field=models.BooleanField(default=False, verbose_name='sticky position'),
        ),
    ]
