# Generated by Django 4.0.7 on 2022-10-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0026_theme_list_filter_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='list_filter_quick_remove',
            field=models.BooleanField(default=True, verbose_name='quick remove'),
        ),
    ]
