# Generated by Django 4.1.3 on 2022-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_interface", "0028_theme_show_fieldsets_as_tabs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="active_dark",
            field=models.BooleanField(default=True),
        ),
    ]
