# Generated by Django 4.1.3 on 2022-12-02 08:49

from django.db import migrations


class Migration(migrations.Migration):
    def create_default_theme(apps, schema_editor):
        Theme = apps.get_model("admin_interface", "Theme")
        instance = Theme.objects.first()
        if not instance:
            Theme.objects.create()

    dependencies = [
        ("admin_interface", "0028_theme_show_fieldsets_as_tabs_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_default_theme, reverse_code=migrations.RunPython.noop
        ),
    ]
