# Generated by Django 4.1.3 on 2022-12-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_interface", "0029_auto_20221202_0849"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theme",
            old_name="css_delete_button_background_color",
            new_name="css_delete_button_bg_color",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="css_delete_button_background_hover_color",
            new_name="css_delete_button_bg_hover_color",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="css_header_background_color",
            new_name="css_header_bg_color",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="css_module_background_color",
            new_name="css_module_bg_color",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="css_module_background_selected_color",
            new_name="css_module_bg_selected_color",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="css_save_button_background_color",
            new_name="css_save_button_bg_color",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="css_save_button_background_hover_color",
            new_name="css_save_button_bg_hover_color",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="related_modal_background_color",
            new_name="related_modal_bg_color",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="related_modal_background_opacity",
            new_name="related_modal_bg_opacity",
        ),
    ]
