# Generated by Django 5.0.3 on 2024-03-19 22:29

import admin_interface.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_interface", "0030_theme_collapsible_stacked_inlines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="static_logo_path",
            field=models.FilePathField(
                blank=True,
                match="^.*\\.(jpg|jpeg|png|svg)$",
                max_length=255,
                path=admin_interface.models.static_logo_directory_path,
                verbose_name="static logo",
            ),
        ),
    ]
