# Generated by Django 5.0.1 on 2024-01-10 10:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_interface", "0031_theme_css_body_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="css_body_foreground_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#333",
                help_text="Default: #333 (required fields, error messages)",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="foreground color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_body_quiet_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#666",
                help_text="Default: #666 (optional fields, help text, field content)",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="quiet color",
            ),
        ),
    ]
