name: Create release

permissions: {}

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    # environment: release
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@273da39a24fb7db106a35526c8162815faffd31d # v3.1.0

      - name: Create release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          token: ${{ secrets.WORKFLOWS_CREATE_RELEASE_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Build Package
        run: |
          pip install pip --upgrade
          pip install build
          python -m build

      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          packages-dir: dist/
          # password: ${{ secrets.WORKFLOWS_PUBLISH_TO_PYPI_TOKEN }}
