name: Test package

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  prepare:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Create matrix
        uses: fabiocaccamo/create-matrix-action@842c9dabf1cec0ba7417f30ec26ce2290b951ef0 # v7
        id: create_matrix
        with:
          matrix: |
            python-version {3.10}, django-version {4.2, 5.0, 5.1, 5.2}, database {sqlite, postgres}
            python-version {3.11}, django-version {4.2, 5.0, 5.1, 5.2}, database {sqlite, postgres}
            python-version {3.12}, django-version {4.2, 5.0, 5.1, 5.2, 6.0}, database {sqlite, postgres}
            python-version {3.13}, django-version {5.1, 5.2, 6.0}, database {sqlite, postgres}
            python-version {3.14}, django-version {5.2, 6.0}, database {sqlite, postgres}

    outputs:
      matrix: ${{ steps.create_matrix.outputs.matrix }}


  lint:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install tools needed
      run: |
        sudo apt install gettext
        python -m pip install --upgrade pip
        pip install tox

    - name: Check migrations
      run: |
        tox -e migrations

    - name: Check translations
      run: |
        tox -e translations


  test:

    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.prepare.outputs.matrix)}}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install psycopg2 prerequisites
      run: sudo apt install libpq-dev

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Upgrade pip version
      run: |
        pip install pip --upgrade

    - name: Install django
      run: |
        pip install "Django == ${{ matrix.django-version }}.*"

    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run pre-commit
      run: |
        pre-commit run --all-files --show-diff-on-failure --verbose

    - name: Run tests
      env:
        DATABASE_ENGINE: ${{ matrix.database }}
      run: |
        coverage run --append --source=admin_interface runtests.py
        coverage report --show-missing
        coverage xml -o ./coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        files: ./coverage.xml
        flags: unittests
        verbose: true
